### ISSUE TITLE
Node.js: abscent de l'installation

### ISSUE THREAD

**Issue by geekmag** [geekmag/RecaToolBox#14]
Après installation la nouvelle arbo est crée mais il manque les fichiers qui vont dans
/recalbox/share/RecaToolBox/ToolBox/RecaNode

**Comment by geekmag** [comment]
Génération de la liste des jeux KO avec l'erreur:


Veuillez patienter. La liste des jeux est en cours de génération
module.js:471
    throw err;
    ^

Error: Cannot find module 'webtorrent'

**Comment by Jey2k** [comment]
Tu peux essayer un "npm install" dans le répertoire principal, puis
relancer le script de build et m'envoyer la sortie du script... Merciiiii

**Comment by geekmag** [comment]
Voilà ce que ça me donne (fait avec le bash Ubuntu sous Windows 10 ^^)

Nous allons packager le NodeJs
Nous sommes maintenant dans le répertoire /mnt/d/RecaToolBox/RecaToolBox/Node

> RecaNodeRoolBox@0.1.0 build /mnt/d/RecaToolBox/RecaToolBox/Node
> webpack

/usr/bin/env: «node»: Aucun fichier ou dossier de ce type

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! RecaNodeRoolBox@0.1.0 build: `webpack`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the RecaNodeRoolBox@0.1.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the RecaNodeRoolBox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack


----------------
npm WARN install:bufferutil@3.0.3 bufferutil@3.0.3 install: `prebuild-install || node-gyp rebuild`
npm WARN install:bufferutil@3.0.3 Exit status 1

> utf-8-validate@4.0.0 install /mnt/d/RecaToolBox/RecaToolBox/Node/node_modules/utf-8-validate
> prebuild-install || node-gyp rebuild

/usr/bin/env: «node»: Aucun fichier ou dossier de ce type
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp

**Comment by Jey2k** [comment]
Ok, j'ai installé le bash Ubuntu pour tester... C'est effectivement parce qu'il te manque les binaires de NodeJS...
Ce que j'ai du faire pour que ça passe:
```Bash
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
```
et comme je ne l'avais pas encore, j'y ai ajouté un:
```Bash
sudo apt-get install -y dos2unix
dos2unix ./buildInstall.sh
```
Et là, magie de l'informatique, ça a fonctionné ;)
Par contre, je me permets de te conseiller de jouer aussi avec le Git Bash, intégré dans l'installation Git, qui est ma fois fort pratique et bien plus léger ;)

**Comment by geekmag** [comment]
Merci! 
Forcément en installant tout ce qu'il faut ça fonctionne mieux ;)

Ha oui, j'ai pas encore le réflex des outils git, je vais regarder ça ;)

**Comment by geekmag** [comment]
good :)
